---
title: "ML_A2"
output: html_notebook
---


```{r}

data <- read.csv("../COMP30027_2024_asst2_data/train_dataset_no_text.csv")

fullmodel <- lm(imdb_score_binned ~ num_critic_for_reviews + duration + 
    director_facebook_likes + actor_3_facebook_likes + actor_1_facebook_likes + 
    gross + num_voted_users + cast_total_facebook_likes + facenumber_in_poster + 
    num_user_for_reviews + title_year + actor_2_facebook_likes + 
    movie_facebook_likes + average_degree_centrality, data=data)
print(drop1(fullmodel, scope= ~ ., test="F"))
```
Removed average_degree_centrality

```{r}
model2 <- lm(imdb_score_binned ~ num_critic_for_reviews + duration + 
    director_facebook_likes + actor_3_facebook_likes + actor_1_facebook_likes + 
    gross + num_voted_users + cast_total_facebook_likes + facenumber_in_poster + 
    num_user_for_reviews + title_year + actor_2_facebook_likes + 
    movie_facebook_likes, data=data)
print(drop1(model2, scope= ~ ., test="F"))
```
Removed director_facebook_likes

```{r}
model3 <- lm(imdb_score_binned ~ num_critic_for_reviews + duration + 
    actor_3_facebook_likes + actor_1_facebook_likes + 
    gross + num_voted_users + cast_total_facebook_likes + facenumber_in_poster + 
    num_user_for_reviews + title_year + actor_2_facebook_likes + 
    movie_facebook_likes, data=data)
print(drop1(model3, scope= ~ ., test="F"))
```
Removed movie_facebook_likes

```{r}
model4 <- lm(imdb_score_binned ~ num_critic_for_reviews + duration + 
    actor_3_facebook_likes + actor_1_facebook_likes + 
    gross + num_voted_users + cast_total_facebook_likes + facenumber_in_poster + 
    num_user_for_reviews + title_year + actor_2_facebook_likes, data=data)
print(drop1(model4, scope= ~ ., test="F"))
```
Removed actor_3_facebook_likes

```{r}
model5 <- lm(imdb_score_binned ~ num_critic_for_reviews + duration + actor_1_facebook_likes + 
    gross + num_voted_users + cast_total_facebook_likes + facenumber_in_poster + 
    num_user_for_reviews + title_year + actor_2_facebook_likes, data=data)
print(drop1(model5, scope= ~ ., test="F"))
```
Removed facenumber_in_poster

```{r}
model6 <- lm(imdb_score_binned ~ num_critic_for_reviews + duration + actor_1_facebook_likes + 
    gross + num_voted_users + cast_total_facebook_likes + 
    num_user_for_reviews + title_year + actor_2_facebook_likes, data=data)
print(drop1(model6, scope= ~ ., test="F"))
```
Removed actor_2_facebook_likes

```{r}
model7 <- lm(imdb_score_binned ~ num_critic_for_reviews + duration + actor_1_facebook_likes + 
    gross + num_voted_users + cast_total_facebook_likes + 
    num_user_for_reviews + title_year, data=data)
print(drop1(model7, scope= ~ ., test="F"))
```
Removed actor_1_facebook_likes

```{r}
model8 <- lm(imdb_score_binned ~ num_critic_for_reviews + duration + 
    gross + num_voted_users + cast_total_facebook_likes + 
    num_user_for_reviews + title_year, data=data)
print(drop1(model8, scope= ~ ., test="F"))
```
Removed cast_total_facebook_likes

```{r}
model9 <- lm(imdb_score_binned ~ num_critic_for_reviews + duration + 
    gross + num_voted_users + num_user_for_reviews + title_year, data=data)
print(drop1(model9, scope= ~ ., test="F"))
```

